# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

label_cpp <- function(mat, nbmask, wrap) {
    .Call('_RandomClustering_label_cpp', PACKAGE = 'RandomClustering', mat, nbmask, wrap)
}

